export enum GameStatus {
    UNINITIALIZED = "UNINITIALIZED", 
    INITIALIZING = "INITIALIZING", 
    RUNNING = "RUNNING", 
    PAUSED = "PAUSED", 
    STORING = "STORING", 
    CLOSED = "CLOSED", 
}
